name: Preview Environment

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  preview:
    runs-on: ubuntu-latest
    environment: preview
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build:prod

      - name: Install DFX
        run: |
          wget https://internetcomputer.org/install.sh
          bash install.sh
          echo "$HOME/bin" >> $GITHUB_PATH

      - name: Deploy to Preview Network
        env:
          DFX_IDENTITY: ${{ secrets.DFX_IDENTITY }}
        run: |
          echo "$DFX_IDENTITY" > identity.pem
          dfx identity import preview identity.pem
          dfx identity use preview
          dfx deploy --network ic --no-wallet
          rm identity.pem

      - name: Comment Preview URL
        uses: actions/github-script@v6
        with:
          script: |
            const canisterId = process.env.CANISTER_ID
            const comment = `🚀 Preview environment deployed!\n\nURL: https://${canisterId}.ic0.app`
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            })
